version: "3.8"

services:
  web-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - REDIS_URL=redis://redis:6379
  redis:
    image: redis
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
volumes:
  redis-data:
    driver: local
